# Generated by Django 2.1.7 on 2019-04-22 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalValue', models.IntegerField(verbose_name='Valor total')),
                ('cuantity', models.IntegerField(verbose_name='Cantidad')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nombre')),
                ('value', models.IntegerField(verbose_name='Valor')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('stock', models.IntegerField(verbose_name='Existencia')),
                ('available', models.BooleanField(verbose_name='Disponible')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='SalesCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalToPay', models.IntegerField(verbose_name='Total a pagar')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de venta')),
                ('lines', models.ManyToManyField(to='products.Line', verbose_name='Linea')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.AddField(
            model_name='line',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_product', to='products.Product', verbose_name='Producto'),
        ),
    ]
