# Generated by Django 2.1.7 on 2019-04-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='totalValue',
            field=models.BigIntegerField(verbose_name='Valor total'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.BigIntegerField(verbose_name='Existencia'),
        ),
        migrations.AlterField(
            model_name='salescheck',
            name='totalToPay',
            field=models.BigIntegerField(verbose_name='Total a pagar'),
        ),
    ]
