# Generated by Django 2.1.7 on 2019-04-24 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190422_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductXLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nombre')),
                ('value', models.BigIntegerField(verbose_name='Valor')),
            ],
        ),
        migrations.AlterField(
            model_name='line',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_product', to='products.ProductXLine', verbose_name='Producto'),
        ),
    ]
