# Generated by Django 2.1.7 on 2019-04-26 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190424_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='line',
            options={'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.RemoveField(
            model_name='salescheck',
            name='lines',
        ),
        migrations.AddField(
            model_name='line',
            name='salesCheck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='products.SalesCheck'),
        ),
        migrations.AddField(
            model_name='line',
            name='value',
            field=models.BigIntegerField(default=0, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='line',
            name='product',
            field=models.CharField(max_length=64, verbose_name='Nombre'),
        ),
        migrations.DeleteModel(
            name='ProductXLine',
        ),
    ]
